### ISSUE TITLE
Is PW_CACHE_EXPIRE=0 not possible? (Proxy)

### ISSUE THREAD

**Issue by erikgieseler** [jasonacox/pypowerwall#122]
Is it not possible to permanently deactivate the cache with PW_CACHE_EXPIRE=0?
I have set this in the environment variables as a test, but the debug log still shows that cached values have been taken.
It also looks as if 5 seconds are cached anyway, even with a lower value.
My docker-compose.yml looks like this:

```
version: "3"

services:
  pypowerwall:
    image: jasonacox/pypowerwall:latest
    container_name: pypowerwall
    hostname: pypowerwall
    ports:
      - 8675:8675
    environment:
      - PW_PORT=8675
      - PW_HOST=192.168.91.1
      - PW_GW_PWD=123
      - PW_CACHE_EXPIRE=0
      - PW_TIMEZONE=Europe/Berlin
      - TZ=Europe/Berlin      
      - PW_DEBUG=yes
    restart: always
```
